### ISSUE TITLE
Create a list of glossaries

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-fish-tools/data_dictionary#18]
Please add links to all glossaries you find here so we can create an archived list somewhere in the future rather than in the google doc.

### Tasks include

- [ ] populating the list to a "large" extent though not exhaustive
- [ ] determining where the list should be kept, potentially even just deciding to leave it here as searchable issue with an appropriate label
- [ ] removing the current list from the google doc
- [ ] broadcasting that we welcome contributions to the list

**Comment by kellijohnson-NOAA** [comment]
* [harveststrategies.org](https://harveststrategies.org/what-are-harvest-strategies/glossary/)
* [awe.gov.au](https://www.awe.gov.au/abares/research-topics/fisheries/fishery-status/glossary-acronyms#glossary)
* [fishbase](https://www.fishbase.in/manual/fishbaselist_of_symbols_and_abbreviation.htm)
* [pewtrusts.org](https://www.pewtrusts.org/~/media/legacy/uploadedfiles/peg/publications/report/AGuidetoFisheriesStockAssessmentpdf.pdf)
* [Cochrane, 2002](https://www.fao.org/documents/card/en/c/bb0bbac3-950c-57e3-81e9-471abd395ae7/)
* [iphc](https://iphc.int/the-commission/glossary-of-terms-and-abbreviations)
* [ICES](https://www.ices.dk/community/Documents/Advice/Acronyms_and_terminology.pdf)
* [safmc](https://safmc.net/frequently-used-acronyms-in-fisheries-management/)
* [Ragonese and Vitale, 2013](https://www.scirp.org/html/7-3000469_35705.htm)

**Comment by GiselleSchmitz-NOAA** [comment]
Is there a particular scope of interest for glossaries?
[FSC@EDF](https://fisherysolutionscenter.edf.org/catch-share-basics/glossary)
[FAO](https://www.fao.org/faoterm/collection/fisheries/en/)
